package com.jeefw.controller.sys;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.net.ssl.HttpsURLConnection;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.DefaultHttpClient;
import org.springframework.stereotype.Controller;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.params.HttpParams;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonRawValue;
import org.codehaus.jackson.map.ObjectMapper;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.jeefw.core.Constant;
import com.jeefw.core.JavaEEFrameworkBaseController;
import com.jeefw.model.sys.SysUser; 
import com.jeefw.service.sys.QuestionService;

import net.sf.json.JSONArray;
import net.sf.json.JSONObject; 

import lombok.Data;

/**
 * @author John
 * @Slack Redirect Response
 */
@Controller
@RequestMapping("/question")
public class SlackResponseController extends JavaEEFrameworkBaseController<SysUser> implements Constant { 

	@Resource
	private QuestionService questionService;
	
	@RequestMapping("/get")
	public void get(HttpServletRequest request, HttpServletResponse response) throws IOException {
		Map<String, Object> result = new HashMap<String, Object>();  
		result.put("result", 200);
		writeJSON(response, result);
	}
	
	
	@RequestMapping(value = "/ask", method = { RequestMethod.POST})
	public void ask(HttpServletRequest request, HttpServletResponse response) throws IOException {  
		Map<String, Object> result = new HashMap<String, Object>();
		// result.put("result", 200);
		String inputText = request.getParameter("text");
		result.put("text", questionService.queryByQuestionContent(inputText));
		result.put("inputtext", inputText);
		// result.put("username", request.getParameter("user_name"));
		// result.put("mrkdwn", true);
		writeJSON(response, result);
	}
	

	/* 
	 * all the parameter below are inside payload
	 * type - to differentiate from other interactive components, look for the string value dialog_submission.
	 * submission - a hash of key/value pairs representing the user's submission. Each key is a name field your app provided when composing the form. Each value is the user's submitted value, or in the case of a select menu, the value you assigned to a specific response.
	 * callback_id - this value is the unique callback_id identifier your app gave this instance of the dialog.
	 * team - this simple hash contains the id and name of the workspace from which this interaction occurred
	 * user - this simple hash contains the id and name of the user who completed the form
	 * channel - this simple hash contains the id and name of the channel or conversation where this dialog was completed
	 * action_ts - this is a unique identifier for this specific action occurrence generated by Slack. It can be evaluated as a timestamp with milliseconds if that is helpful to you.
	 * token - the verification token shared between your app and Slack used to validate an incoming request originates from Slack.
	 */
	@RequestMapping(value = "/update", method = { RequestMethod.POST})
	public void update(HttpServletRequest request, HttpServletResponse response) throws IOException {  
		Map<String, Object> result = new HashMap<String, Object>();
		// result.put("result", 200);
		String payload = request.getParameter("payload");
		JSONParser parser = new JSONParser();
		try {
			org.json.simple.JSONObject jsonPayload = (org.json.simple.JSONObject) parser.parse(payload);   
			String callback_id = (String) jsonPayload.get("callback_id");
			switch(callback_id) {
			case "create":
				break;
			case "update":
				// need existing question id and answer id
				break;
			}
			String user_id = (String) jsonPayload.get("user"); 
			String question = (String) ((org.json.simple.JSONObject)jsonPayload.get("submission")).get("question");
			String answer = (String) ((org.json.simple.JSONObject)jsonPayload.get("submission")).get("answer"); 
			System.out.println("user_id: " + user_id);
			System.out.println("question: " + question);
			System.out.println("answer: " + answer);
		} catch (ParseException e) { 
			e.printStackTrace();
		} 
		
		writeJSON(response, result);
	} 
	
	/*
	 * Available parameter for request
	 * token=gIkuvaNzQIHg97ATvDxqgjtO
	 * team_id=T0001
	 * team_domain=example
	 * enterprise_id=E0001
	 * enterprise_name=Globular%20Construct%20Inc
	 * channel_id=C2147483705
	 * channel_name=test
	 * user_id=U2147483697
	 * user_name=Steve
	 * command=/weather
	 * text=94070
	 * response_url=https://hooks.slack.com/commands/1234/5678
	 * trigger_id=13345224609.738474920.8088930838d88f008e0
	 */
	@RequestMapping(value = "/opendialog", method = { RequestMethod.POST})
	public void opendialog(HttpServletRequest request, HttpServletResponse response) throws IOException {  
		Map<String, Object> result = new HashMap<String, Object>();
		// result.put("result", 200);
		String trigger_id = request.getParameter("trigger_id");
		String token = request.getParameter("token"); 
		
		JSONObject dialog = new JSONObject();
		dialog.put("callback_id", "create");
		dialog.put("title", "New question and answer");
		JSONArray elements = new JSONArray();
		JSONObject elementQuestion = new JSONObject(); 
		elementQuestion.put( "type", "text");
		elementQuestion.put("label", "Question");
		elementQuestion.put("name", "question"); // will be used for create request, included in the payload
		elements.add(elementQuestion);
		JSONObject elementAnswer = new JSONObject(); 
		elementAnswer.put( "type", "textarea");
		elementAnswer.put("label", "Answer");
		elementAnswer.put("name", "answer"); // will be used for create request, included in the payload
		elementAnswer.put("hint", "Provide answer for your question.");
		elements.add(elementAnswer);
		dialog.put("elements", elements);  
		
		try {
			sendPost(trigger_id, getJsonObject(dialog));
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	
//	// HTTP POST request
//	// Java HttpURLConnection
//	private void sendPost(String trigger_id, String dialog) throws Exception {
//
//		String url = "https://slack.com/api/dialog.open";
//		URL obj = new URL(url);
//		HttpsURLConnection con = (HttpsURLConnection) obj.openConnection(); 
//		
//		//add request header
//		con.setRequestMethod("POST");
//		con.setRequestProperty("User-Agent", "Mozilla/5.0"); 
//		con.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
//		con.setRequestProperty("Authorization", "Bearer xoxa-69335041190-321290058903-321290059191-992bed1f9cd43ccd948fbb468f955542");
//		con.setRequestProperty("Accept-Charset", "UTF-8"); 
//
//		String urlParameters =  "trigger_id=" + trigger_id
//								+ "&dialog=" + dialog;
//
//		// Send post request
//		con.setDoOutput(true);
//		DataOutputStream wr = new DataOutputStream(con.getOutputStream());
//		wr.writeBytes(urlParameters);
//		wr.flush();
//		wr.close();
//
//		int responseCode = con.getResponseCode();
//		System.out.println("\nSending 'POST' request to URL : " + url);
//		System.out.println("Post parameters : " + urlParameters);
//		System.out.println("Dialog : " + dialog);
//		System.out.println("Response Code : " + responseCode);
//
//		BufferedReader in = new BufferedReader(
//		        new InputStreamReader(con.getInputStream()));
//		String inputLine;
//		StringBuffer response = new StringBuffer();
//
//		while ((inputLine = in.readLine()) != null) {
//			response.append(inputLine);
//		}
//		in.close(); 
//	}
	
	// HTTP POST request
	// Apache HttpClient
	private void sendPost(String trigger_id, String dialog) {

		String url = "https://slack.com/api/dialog.open";
		HttpClient client = new DefaultHttpClient();
		HttpPost post = new HttpPost(url);

		// add header 
		post.addHeader("User-Agent", "Mozilla/5.0"); 
		post.addHeader("Content-Type", "application/x-www-form-urlencoded");
		post.addHeader("Authorization", "Bearer xoxa-69335041190-321290058903-321290059191-992bed1f9cd43ccd948fbb468f955542");
		post.addHeader("Accept-Charset", "UTF-8"); 

		List<BasicNameValuePair> urlParameters = new ArrayList<BasicNameValuePair>();
		urlParameters.add(new BasicNameValuePair("trigger_id", trigger_id));
		urlParameters.add(new BasicNameValuePair("dialog", dialog)); 
		
		try {
			post.setEntity(new UrlEncodedFormEntity(urlParameters));  
			HttpResponse response = client.execute(post);
			System.out.println("\nSending 'POST' request to URL : " + url);
			System.out.println("Post parameters : " + post.getEntity());
			System.out.println("Response Code : " +
	                                    response.getStatusLine().getStatusCode());

			BufferedReader rd = new BufferedReader(
	                        new InputStreamReader(response.getEntity().getContent()));

			StringBuffer result = new StringBuffer();
			String line = "";
			while ((line = rd.readLine()) != null) {
				result.append(line);
			}

			System.out.println(result.toString());
		} catch (UnsupportedEncodingException e) { 
			e.printStackTrace();
		} catch (IOException e) { 
			e.printStackTrace();
		}
		
	}
	
	@JsonRawValue 
    @JsonProperty(value = "jsonString")
    public String getJsonObject(JSONObject jsonObject)
    {
         return jsonObject.toString();
    } 
}
